#!/usr/bin/env python3
"""
FFXI-Server Advanced AI Game Masters - Iteration 13
===================================================

AI-powered dynamic event generation, intelligent NPC behavior and storytelling,
adaptive difficulty and content scaling, and real-time player experience optimization.

Part of: Iteration 13 - Advanced AI & Automation
Timeline: Q2 2025 Implementation
Status: Core AI Game Master framework
"""

import os
import sys
import json
import time
import random
import sqlite3
import logging
import threading
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, asdict
from enum import Enum
import hashlib


class EventType(Enum):
    """Types of dynamic events the AI can generate."""

    TREASURE_HUNT = "treasure_hunt"
    INVASION = "invasion"
    WEATHER_EVENT = "weather_event"
    RARE_SPAWN = "rare_spawn"
    SOCIAL_GATHERING = "social_gathering"
    QUEST_CHAIN = "quest_chain"
    SEASONAL_EVENT = "seasonal_event"
    ECONOMIC_SHIFT = "economic_shift"


class DifficultyLevel(Enum):
    """Adaptive difficulty levels."""

    TRIVIAL = 1
    EASY = 2
    MODERATE = 3
    CHALLENGING = 4
    HARD = 5
    EXTREME = 6


@dataclass
class PlayerProfile:
    """Player profile for experience optimization."""

    player_id: int
    name: str
    level: int
    job: str
    playtime_hours: int
    preferred_content: List[str]
    skill_rating: float  # 0.0 to 1.0
    social_preference: float  # 0.0 (solo) to 1.0 (group)
    challenge_preference: float  # 0.0 (easy) to 1.0 (hard)
    last_seen: datetime
    engagement_score: float


@dataclass
class DynamicEvent:
    """Dynamic event generated by AI."""

    event_id: str
    event_type: EventType
    title: str
    description: str
    zone_id: int
    zone_name: str
    start_time: datetime
    duration_minutes: int
    max_participants: int
    min_level: int
    max_level: int
    rewards: Dict[str, Any]
    conditions: Dict[str, Any]
    story_elements: List[str]
    difficulty: DifficultyLevel
    target_players: List[int]


@dataclass
class NPCBehavior:
    """Intelligent NPC behavior profile."""

    npc_id: int
    personality_traits: Dict[str, float]
    dialogue_style: str
    reaction_patterns: Dict[str, str]
    memory_capacity: int
    learning_rate: float
    social_connections: List[int]
    current_mood: str
    story_involvement: float


@dataclass
class StoryElement:
    """Dynamic story element for events."""

    element_id: str
    element_type: str  # character, plot, setting, conflict
    content: str
    connections: List[str]
    importance: float
    used_count: int
    player_impact: Dict[int, float]


class AdvancedAIGameMaster:
    """Advanced AI Game Master with dynamic content generation."""

    def __init__(self, config_path: Optional[str] = None):
        self.config = self._load_config(config_path)
        self.db_path = Path(__file__).parent / "ai_gamemaster.db"
        self.running = False
        self.threads = []

        # Initialize logging
        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)s - %(levelname)s - %(message)s",
            handlers=[
                logging.FileHandler("ai_gamemaster.log"),
                logging.StreamHandler(sys.stdout),
            ],
        )
        self.logger = logging.getLogger(__name__)

        # Initialize database
        self._init_database()

        # Story generation components
        self.story_templates = self._load_story_templates()
        self.character_archetypes = self._load_character_archetypes()
        self.plot_devices = self._load_plot_devices()

        # NPC AI state
        self.npc_behaviors = {}
        self.active_events = {}
        self.player_profiles = {}

        # Event generation parameters
        self.event_frequency = {
            EventType.TREASURE_HUNT: 0.3,  # 30% chance per check
            EventType.INVASION: 0.1,  # 10% chance per check
            EventType.WEATHER_EVENT: 0.4,  # 40% chance per check
            EventType.RARE_SPAWN: 0.2,  # 20% chance per check
            EventType.SOCIAL_GATHERING: 0.25,  # 25% chance per check
            EventType.QUEST_CHAIN: 0.15,  # 15% chance per check
            EventType.SEASONAL_EVENT: 0.05,  # 5% chance per check
            EventType.ECONOMIC_SHIFT: 0.08,  # 8% chance per check
        }

    def _load_config(self, config_path: Optional[str]) -> Dict:
        """Load AI Game Master configuration."""
        default_config = {
            "event_generation_interval": 300,  # 5 minutes
            "max_concurrent_events": 5,
            "player_analysis_interval": 600,  # 10 minutes
            "npc_behavior_update_interval": 180,  # 3 minutes
            "story_coherence_weight": 0.7,
            "player_preference_weight": 0.8,
            "difficulty_adaptation_rate": 0.1,
            "social_event_threshold": 3,  # min players for social events
            "engagement_decay_rate": 0.95,
            "learning_rate": 0.01,
        }

        if config_path and os.path.exists(config_path):
            try:
                with open(config_path, "r") as f:
                    user_config = json.load(f)
                default_config.update(user_config)
            except Exception as e:
                self.logger.warning(f"Failed to load config: {e}")

        return default_config

    def _init_database(self):
        """Initialize SQLite database for AI Game Master data."""
        with sqlite3.connect(self.db_path) as conn:
            conn.executescript(
                """
                CREATE TABLE IF NOT EXISTS player_profiles (
                    player_id INTEGER PRIMARY KEY,
                    name TEXT NOT NULL,
                    level INTEGER,
                    job TEXT,
                    playtime_hours INTEGER,
                    preferred_content TEXT,
                    skill_rating REAL,
                    social_preference REAL,
                    challenge_preference REAL,
                    last_seen DATETIME,
                    engagement_score REAL,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
                );
                
                CREATE TABLE IF NOT EXISTS dynamic_events (
                    event_id TEXT PRIMARY KEY,
                    event_type TEXT NOT NULL,
                    title TEXT NOT NULL,
                    description TEXT,
                    zone_id INTEGER,
                    zone_name TEXT,
                    start_time DATETIME,
                    duration_minutes INTEGER,
                    max_participants INTEGER,
                    min_level INTEGER,
                    max_level INTEGER,
                    rewards TEXT,
                    conditions TEXT,
                    story_elements TEXT,
                    difficulty INTEGER,
                    target_players TEXT,
                    status TEXT DEFAULT 'planned',
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
                );
                
                CREATE TABLE IF NOT EXISTS npc_behaviors (
                    npc_id INTEGER PRIMARY KEY,
                    personality_traits TEXT,
                    dialogue_style TEXT,
                    reaction_patterns TEXT,
                    memory_capacity INTEGER,
                    learning_rate REAL,
                    social_connections TEXT,
                    current_mood TEXT,
                    story_involvement REAL,
                    last_interaction DATETIME,
                    interaction_count INTEGER DEFAULT 0,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
                );
                
                CREATE TABLE IF NOT EXISTS story_elements (
                    element_id TEXT PRIMARY KEY,
                    element_type TEXT NOT NULL,
                    content TEXT NOT NULL,
                    connections TEXT,
                    importance REAL,
                    used_count INTEGER DEFAULT 0,
                    player_impact TEXT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
                );
                
                CREATE TABLE IF NOT EXISTS player_interactions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    player_id INTEGER,
                    event_id TEXT,
                    npc_id INTEGER,
                    interaction_type TEXT,
                    success_rate REAL,
                    satisfaction_score REAL,
                    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
                );
                
                CREATE TABLE IF NOT EXISTS event_outcomes (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    event_id TEXT NOT NULL,
                    participants INTEGER,
                    success_rate REAL,
                    player_satisfaction REAL,
                    story_coherence REAL,
                    economic_impact REAL,
                    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
                );
                
                CREATE INDEX IF NOT EXISTS idx_player_last_seen 
                ON player_profiles(last_seen);
                CREATE INDEX IF NOT EXISTS idx_events_start_time 
                ON dynamic_events(start_time);
                CREATE INDEX IF NOT EXISTS idx_interactions_timestamp 
                ON player_interactions(timestamp);
            """
            )

    def _load_story_templates(self) -> Dict[str, List[str]]:
        """Load story templates for dynamic content generation."""
        return {
            "treasure_hunt": [
                "A mysterious map has been discovered pointing to ancient treasure in {zone}",
                "Local reports suggest valuable artifacts buried in {zone}",
                "Ancient texts speak of legendary items hidden in {zone}",
                "A dying adventurer whispers of riches concealed in {zone}",
            ],
            "invasion": [
                "Enemy forces have been spotted gathering near {zone}",
                "Dark creatures are amassing for an assault on {zone}",
                "Intelligence reports suggest an imminent attack on {zone}",
                "Scouts report unusual enemy activity threatening {zone}",
            ],
            "social_gathering": [
                "The people of {zone} are celebrating a local festival",
                "A renowned merchant has established a temporary market in {zone}",
                "Adventurers are gathering to share tales and knowledge in {zone}",
                "A famous performer is hosting entertainment in {zone}",
            ],
            "quest_chain": [
                "A mysterious figure seeks brave souls to uncover the truth about {zone}",
                "Ancient prophecies speak of heroes who will emerge in {zone}",
                "A series of strange events in {zone} requires investigation",
                "Local authorities need assistance with escalating problems in {zone}",
            ],
        }

    def _load_character_archetypes(self) -> Dict[str, Dict]:
        """Load character archetypes for NPC behavior."""
        return {
            "wise_mentor": {
                "personality": {"wisdom": 0.9, "patience": 0.8, "kindness": 0.7},
                "dialogue_style": "thoughtful",
                "preferred_interactions": ["guidance", "teaching", "advice"],
            },
            "gruff_warrior": {
                "personality": {"bravery": 0.9, "stubbornness": 0.7, "loyalty": 0.8},
                "dialogue_style": "direct",
                "preferred_interactions": ["combat", "challenges", "honor"],
            },
            "cunning_merchant": {
                "personality": {"greed": 0.6, "intelligence": 0.8, "charisma": 0.7},
                "dialogue_style": "persuasive",
                "preferred_interactions": ["trading", "information", "profit"],
            },
            "mysterious_sage": {
                "personality": {"knowledge": 0.9, "secrecy": 0.8, "power": 0.6},
                "dialogue_style": "cryptic",
                "preferred_interactions": ["riddles", "magic", "prophecy"],
            },
            "friendly_villager": {
                "personality": {"helpfulness": 0.8, "curiosity": 0.6, "fear": 0.4},
                "dialogue_style": "casual",
                "preferred_interactions": ["gossip", "assistance", "community"],
            },
        }

    def _load_plot_devices(self) -> List[str]:
        """Load plot devices for story generation."""
        return [
            "ancient_curse",
            "lost_artifact",
            "prophetic_dream",
            "betrayal",
            "hidden_identity",
            "forbidden_love",
            "quest_for_power",
            "redemption_arc",
            "time_paradox",
            "sacrifice",
            "discovery",
            "revenge",
            "protection",
            "transformation",
            "alliance",
        ]

    def load_player_profiles(self):
        """Load player profiles from database or game data."""
        try:
            with sqlite3.connect(self.db_path) as conn:
                rows = conn.execute(
                    """
                    SELECT * FROM player_profiles 
                    WHERE last_seen > datetime('now', '-7 days')
                """
                ).fetchall()

                for row in rows:
                    player_id = row[0]
                    self.player_profiles[player_id] = PlayerProfile(
                        player_id=row[0],
                        name=row[1],
                        level=row[2],
                        job=row[3],
                        playtime_hours=row[4],
                        preferred_content=json.loads(row[5]) if row[5] else [],
                        skill_rating=row[6],
                        social_preference=row[7],
                        challenge_preference=row[8],
                        last_seen=datetime.fromisoformat(row[9]),
                        engagement_score=row[10],
                    )

                self.logger.info(f"Loaded {len(self.player_profiles)} player profiles")
        except Exception as e:
            self.logger.error(f"Failed to load player profiles: {e}")

    def analyze_player_engagement(self):
        """Analyze and update player engagement patterns."""
        try:
            current_time = datetime.now()

            for player_id, profile in self.player_profiles.items():
                # Calculate engagement decay
                time_since_seen = (
                    current_time - profile.last_seen
                ).total_seconds() / 3600
                decay_factor = self.config["engagement_decay_rate"] ** time_since_seen
                profile.engagement_score *= decay_factor

                # Analyze interaction patterns
                with sqlite3.connect(self.db_path) as conn:
                    interactions = conn.execute(
                        """
                        SELECT interaction_type, success_rate, satisfaction_score
                        FROM player_interactions 
                        WHERE player_id = ? AND timestamp > datetime('now', '-24 hours')
                    """,
                        (player_id,),
                    ).fetchall()

                    if interactions:
                        avg_satisfaction = sum(i[2] for i in interactions) / len(
                            interactions
                        )
                        avg_success = sum(i[1] for i in interactions) / len(
                            interactions
                        )

                        # Update engagement based on recent performance
                        engagement_boost = (avg_satisfaction + avg_success) / 2 * 0.1
                        profile.engagement_score += engagement_boost
                        profile.engagement_score = min(
                            1.0, max(0.0, profile.engagement_score)
                        )

                # Update skill rating based on recent performance
                self._update_skill_rating(profile)

        except Exception as e:
            self.logger.error(f"Player engagement analysis failed: {e}")

    def _update_skill_rating(self, profile: PlayerProfile):
        """Update player skill rating based on performance."""
        try:
            with sqlite3.connect(self.db_path) as conn:
                recent_events = conn.execute(
                    """
                    SELECT success_rate FROM player_interactions 
                    WHERE player_id = ? AND timestamp > datetime('now', '-7 days')
                """,
                    (profile.player_id,),
                ).fetchall()

                if recent_events:
                    avg_success = sum(r[0] for r in recent_events) / len(recent_events)
                    learning_rate = self.config["learning_rate"]

                    # Adaptive skill rating update
                    profile.skill_rating += learning_rate * (
                        avg_success - profile.skill_rating
                    )
                    profile.skill_rating = min(1.0, max(0.0, profile.skill_rating))

        except Exception as e:
            self.logger.error(f"Skill rating update failed: {e}")

    def generate_dynamic_event(self) -> Optional[DynamicEvent]:
        """Generate a dynamic event based on current game state and player needs."""
        try:
            # Check if we should generate an event
            if len(self.active_events) >= self.config["max_concurrent_events"]:
                return None

            # Select event type based on player activity and preferences
            event_type = self._select_event_type()
            if not event_type:
                return None

            # Generate event details
            event_id = self._generate_event_id(event_type)
            zone_info = self._select_optimal_zone(event_type)

            # Create story elements
            story_elements = self._generate_story_elements(event_type, zone_info)

            # Determine target players
            target_players = self._select_target_players(event_type)

            # Calculate difficulty
            difficulty = self._calculate_adaptive_difficulty(target_players)

            # Generate rewards
            rewards = self._generate_rewards(
                event_type, difficulty, len(target_players)
            )

            # Create event
            event = DynamicEvent(
                event_id=event_id,
                event_type=event_type,
                title=self._generate_event_title(event_type, zone_info),
                description=self._generate_event_description(
                    event_type, zone_info, story_elements
                ),
                zone_id=zone_info["id"],
                zone_name=zone_info["name"],
                start_time=datetime.now() + timedelta(minutes=random.randint(5, 30)),
                duration_minutes=self._calculate_event_duration(event_type),
                max_participants=self._calculate_max_participants(event_type),
                min_level=max(
                    1,
                    min(
                        p.level
                        for p in [self.player_profiles[pid] for pid in target_players]
                    )
                    - 5,
                ),
                max_level=max(
                    p.level
                    for p in [self.player_profiles[pid] for pid in target_players]
                )
                + 10,
                rewards=rewards,
                conditions=self._generate_event_conditions(event_type),
                story_elements=story_elements,
                difficulty=difficulty,
                target_players=target_players,
            )

            self.active_events[event_id] = event
            self._store_event(event)

            self.logger.info(
                f"Generated dynamic event: {event.title} in {event.zone_name}"
            )
            return event

        except Exception as e:
            self.logger.error(f"Event generation failed: {e}")
            return None

    def _select_event_type(self) -> Optional[EventType]:
        """Select event type based on current conditions and player needs."""
        # Analyze current player activity
        active_players = len(
            [
                p
                for p in self.player_profiles.values()
                if (datetime.now() - p.last_seen).total_seconds() < 3600
            ]
        )

        if active_players < self.config["social_event_threshold"]:
            # Prefer solo events when few players online
            weights = {
                EventType.TREASURE_HUNT: 0.4,
                EventType.RARE_SPAWN: 0.3,
                EventType.QUEST_CHAIN: 0.2,
                EventType.WEATHER_EVENT: 0.1,
            }
        else:
            # Prefer group events when many players online
            weights = {
                EventType.INVASION: 0.25,
                EventType.SOCIAL_GATHERING: 0.2,
                EventType.TREASURE_HUNT: 0.15,
                EventType.QUEST_CHAIN: 0.15,
                EventType.RARE_SPAWN: 0.1,
                EventType.WEATHER_EVENT: 0.1,
                EventType.SEASONAL_EVENT: 0.03,
                EventType.ECONOMIC_SHIFT: 0.02,
            }

        # Select event type randomly based on weights
        event_types = list(weights.keys())
        event_weights = list(weights.values())

        return random.choices(event_types, weights=event_weights)[0]

    def _select_optimal_zone(self, event_type: EventType) -> Dict:
        """Select optimal zone for the event based on player distribution."""
        # Mock zone data - in real implementation, this would query game database
        zones = [
            {
                "id": 1,
                "name": "West Ronfaure",
                "level_range": (1, 10),
                "type": "outdoor",
            },
            {
                "id": 2,
                "name": "East Ronfaure",
                "level_range": (5, 15),
                "type": "outdoor",
            },
            {
                "id": 3,
                "name": "La Theine Plateau",
                "level_range": (10, 20),
                "type": "outdoor",
            },
            {
                "id": 4,
                "name": "Valkurm Dunes",
                "level_range": (15, 25),
                "type": "outdoor",
            },
            {
                "id": 5,
                "name": "Buburimu Peninsula",
                "level_range": (20, 30),
                "type": "outdoor",
            },
            {
                "id": 6,
                "name": "Qufim Island",
                "level_range": (25, 35),
                "type": "outdoor",
            },
            {"id": 7, "name": "Jeuno", "level_range": (1, 75), "type": "city"},
        ]

        # Filter zones based on event type
        if event_type == EventType.SOCIAL_GATHERING:
            suitable_zones = [z for z in zones if z["type"] == "city"]
        else:
            suitable_zones = [z for z in zones if z["type"] == "outdoor"]

        # Select zone based on player level distribution
        if suitable_zones:
            return random.choice(suitable_zones)
        else:
            return zones[0]  # Fallback

    def _generate_story_elements(
        self, event_type: EventType, zone_info: Dict
    ) -> List[str]:
        """Generate story elements for the event."""
        elements = []

        # Get templates for this event type
        templates = self.story_templates.get(event_type.value, [])
        if templates:
            template = random.choice(templates)
            story = template.format(zone=zone_info["name"])
            elements.append(story)

        # Add plot devices
        if random.random() < 0.6:  # 60% chance for plot device
            plot_device = random.choice(self.plot_devices)
            elements.append(f"plot_device:{plot_device}")

        # Add character involvement
        if random.random() < 0.4:  # 40% chance for character involvement
            archetype = random.choice(list(self.character_archetypes.keys()))
            elements.append(f"character:{archetype}")

        return elements

    def _select_target_players(self, event_type: EventType) -> List[int]:
        """Select target players for the event based on preferences and engagement."""
        suitable_players = []

        for player_id, profile in self.player_profiles.items():
            # Check if player is active
            if (datetime.now() - profile.last_seen).total_seconds() > 7200:  # 2 hours
                continue

            # Check engagement score
            if profile.engagement_score < 0.3:
                continue

            # Check content preferences
            content_match = False
            if event_type.value in profile.preferred_content:
                content_match = True
            elif event_type in [EventType.SOCIAL_GATHERING, EventType.QUEST_CHAIN]:
                if profile.social_preference > 0.6:
                    content_match = True
            elif event_type in [EventType.INVASION, EventType.RARE_SPAWN]:
                if profile.challenge_preference > 0.5:
                    content_match = True

            if content_match:
                suitable_players.append(player_id)

        # Limit to reasonable number of players
        max_targets = min(20, len(suitable_players))
        if len(suitable_players) > max_targets:
            # Select highest engagement players
            suitable_players.sort(
                key=lambda pid: self.player_profiles[pid].engagement_score, reverse=True
            )
            suitable_players = suitable_players[:max_targets]

        return suitable_players

    def _calculate_adaptive_difficulty(
        self, target_players: List[int]
    ) -> DifficultyLevel:
        """Calculate adaptive difficulty based on target players."""
        if not target_players:
            return DifficultyLevel.MODERATE

        avg_skill = sum(
            self.player_profiles[pid].skill_rating for pid in target_players
        ) / len(target_players)
        avg_challenge_pref = sum(
            self.player_profiles[pid].challenge_preference for pid in target_players
        ) / len(target_players)

        # Combine skill and preference
        difficulty_score = avg_skill * 0.6 + avg_challenge_pref * 0.4

        if difficulty_score < 0.2:
            return DifficultyLevel.EASY
        elif difficulty_score < 0.4:
            return DifficultyLevel.MODERATE
        elif difficulty_score < 0.6:
            return DifficultyLevel.CHALLENGING
        elif difficulty_score < 0.8:
            return DifficultyLevel.HARD
        else:
            return DifficultyLevel.EXTREME

    def _generate_event_title(self, event_type: EventType, zone_info: Dict) -> str:
        """Generate an engaging title for the event."""
        titles = {
            EventType.TREASURE_HUNT: [
                f"Treasure Hunt in {zone_info['name']}",
                f"Lost Riches of {zone_info['name']}",
                f"The {zone_info['name']} Treasure Trail",
            ],
            EventType.INVASION: [
                f"Defense of {zone_info['name']}",
                f"The {zone_info['name']} Incursion",
                f"Battle for {zone_info['name']}",
            ],
            EventType.SOCIAL_GATHERING: [
                f"{zone_info['name']} Festival",
                f"Gathering at {zone_info['name']}",
                f"The {zone_info['name']} Celebration",
            ],
            EventType.QUEST_CHAIN: [
                f"The {zone_info['name']} Mystery",
                f"Secrets of {zone_info['name']}",
                f"The {zone_info['name']} Chronicles",
            ],
        }

        event_titles = titles.get(event_type, [f"Event in {zone_info['name']}"])
        return random.choice(event_titles)

    def _generate_event_description(
        self, event_type: EventType, zone_info: Dict, story_elements: List[str]
    ) -> str:
        """Generate detailed event description."""
        base_description = (
            story_elements[0]
            if story_elements
            else f"An event is taking place in {zone_info['name']}"
        )

        # Add story enhancements
        if len(story_elements) > 1:
            for element in story_elements[1:]:
                if element.startswith("plot_device:"):
                    device = element.split(":")[1]
                    base_description += (
                        f" This event involves {device.replace('_', ' ')}."
                    )
                elif element.startswith("character:"):
                    character = element.split(":")[1]
                    base_description += (
                        f" A {character.replace('_', ' ')} plays a key role."
                    )

        return base_description

    def _calculate_event_duration(self, event_type: EventType) -> int:
        """Calculate event duration based on type."""
        durations = {
            EventType.TREASURE_HUNT: 60,  # 1 hour
            EventType.INVASION: 45,  # 45 minutes
            EventType.WEATHER_EVENT: 30,  # 30 minutes
            EventType.RARE_SPAWN: 15,  # 15 minutes
            EventType.SOCIAL_GATHERING: 90,  # 1.5 hours
            EventType.QUEST_CHAIN: 120,  # 2 hours
            EventType.SEASONAL_EVENT: 180,  # 3 hours
            EventType.ECONOMIC_SHIFT: 240,  # 4 hours
        }

        base_duration = durations.get(event_type, 60)
        # Add some randomness
        variation = random.randint(-15, 15)
        return max(15, base_duration + variation)

    def _calculate_max_participants(self, event_type: EventType) -> int:
        """Calculate maximum participants for event."""
        participants = {
            EventType.TREASURE_HUNT: 6,
            EventType.INVASION: 18,
            EventType.WEATHER_EVENT: 12,
            EventType.RARE_SPAWN: 6,
            EventType.SOCIAL_GATHERING: 50,
            EventType.QUEST_CHAIN: 8,
            EventType.SEASONAL_EVENT: 100,
            EventType.ECONOMIC_SHIFT: 999,
        }

        return participants.get(event_type, 12)

    def _generate_rewards(
        self, event_type: EventType, difficulty: DifficultyLevel, participant_count: int
    ) -> Dict[str, Any]:
        """Generate appropriate rewards for the event."""
        base_exp = 1000 * difficulty.value
        base_gil = 500 * difficulty.value

        # Scale rewards based on participant count
        if participant_count > 10:
            base_exp = int(base_exp * 1.2)
            base_gil = int(base_gil * 1.2)

        rewards = {"experience": base_exp, "gil": base_gil, "items": []}

        # Add event-specific rewards
        if event_type == EventType.TREASURE_HUNT:
            rewards["items"].extend(["rare_gem", "ancient_coin"])
        elif event_type == EventType.INVASION:
            rewards["items"].extend(["battle_trophy", "honor_medal"])
        elif event_type == EventType.SOCIAL_GATHERING:
            rewards["items"].extend(["festival_token", "party_favor"])

        return rewards

    def _generate_event_conditions(self, event_type: EventType) -> Dict[str, Any]:
        """Generate event conditions and requirements."""
        conditions = {
            "weather_requirement": None,
            "time_requirement": None,
            "group_size_min": 1,
            "group_size_max": None,
            "special_requirements": [],
        }

        if event_type == EventType.WEATHER_EVENT:
            conditions["weather_requirement"] = random.choice(
                ["rain", "fog", "sandstorm"]
            )
        elif event_type == EventType.INVASION:
            conditions["group_size_min"] = 3
        elif event_type == EventType.SOCIAL_GATHERING:
            conditions["group_size_min"] = 2

        return conditions

    def _generate_event_id(self, event_type: EventType) -> str:
        """Generate unique event ID."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        type_code = event_type.value[:4].upper()
        random_suffix = hashlib.md5(
            f"{timestamp}{random.random()}".encode()
        ).hexdigest()[:6]
        return f"{type_code}_{timestamp}_{random_suffix}"

    def _store_event(self, event: DynamicEvent):
        """Store event in database."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """
                INSERT OR REPLACE INTO dynamic_events 
                (event_id, event_type, title, description, zone_id, zone_name,
                 start_time, duration_minutes, max_participants, min_level, max_level,
                 rewards, conditions, story_elements, difficulty, target_players)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
                (
                    event.event_id,
                    event.event_type.value,
                    event.title,
                    event.description,
                    event.zone_id,
                    event.zone_name,
                    event.start_time.isoformat(),
                    event.duration_minutes,
                    event.max_participants,
                    event.min_level,
                    event.max_level,
                    json.dumps(event.rewards),
                    json.dumps(event.conditions),
                    json.dumps(event.story_elements),
                    event.difficulty.value,
                    json.dumps(event.target_players),
                ),
            )

    def update_npc_behaviors(self):
        """Update NPC behaviors based on player interactions and AI learning."""
        try:
            # This would integrate with actual NPC data in a real implementation
            self.logger.info("Updating NPC behaviors based on AI analysis")

            # For each NPC, analyze recent interactions
            with sqlite3.connect(self.db_path) as conn:
                npcs_with_interactions = conn.execute(
                    """
                    SELECT DISTINCT npc_id FROM player_interactions 
                    WHERE timestamp > datetime('now', '-24 hours')
                """
                ).fetchall()

                for (npc_id,) in npcs_with_interactions:
                    self._update_individual_npc_behavior(npc_id)

        except Exception as e:
            self.logger.error(f"NPC behavior update failed: {e}")

    def _update_individual_npc_behavior(self, npc_id: int):
        """Update individual NPC behavior based on interactions."""
        try:
            with sqlite3.connect(self.db_path) as conn:
                # Get recent interactions
                interactions = conn.execute(
                    """
                    SELECT player_id, interaction_type, success_rate, satisfaction_score
                    FROM player_interactions 
                    WHERE npc_id = ? AND timestamp > datetime('now', '-7 days')
                """,
                    (npc_id,),
                ).fetchall()

                if not interactions:
                    return

                # Calculate interaction statistics
                avg_satisfaction = sum(i[3] for i in interactions) / len(interactions)
                interaction_types = [i[1] for i in interactions]
                most_common_interaction = max(
                    set(interaction_types), key=interaction_types.count
                )

                # Load or create NPC behavior
                npc_behavior = self._load_npc_behavior(npc_id)

                # Update behavior based on interaction success
                if avg_satisfaction > 0.7:
                    # Positive interactions - maintain current personality
                    npc_behavior.story_involvement = min(
                        1.0, npc_behavior.story_involvement + 0.1
                    )
                elif avg_satisfaction < 0.3:
                    # Negative interactions - adjust personality
                    if "helpfulness" in npc_behavior.personality_traits:
                        npc_behavior.personality_traits["helpfulness"] *= 0.9

                # Update dialogue style based on interaction patterns
                if most_common_interaction == "trading":
                    npc_behavior.dialogue_style = "business"
                elif most_common_interaction == "combat":
                    npc_behavior.dialogue_style = "aggressive"
                elif most_common_interaction == "guidance":
                    npc_behavior.dialogue_style = "helpful"

                # Store updated behavior
                self._store_npc_behavior(npc_behavior)

        except Exception as e:
            self.logger.error(
                f"Individual NPC behavior update failed for NPC {npc_id}: {e}"
            )

    def _load_npc_behavior(self, npc_id: int) -> NPCBehavior:
        """Load NPC behavior from database or create default."""
        try:
            with sqlite3.connect(self.db_path) as conn:
                row = conn.execute(
                    """
                    SELECT * FROM npc_behaviors WHERE npc_id = ?
                """,
                    (npc_id,),
                ).fetchone()

                if row:
                    return NPCBehavior(
                        npc_id=row[0],
                        personality_traits=json.loads(row[1]),
                        dialogue_style=row[2],
                        reaction_patterns=json.loads(row[3]),
                        memory_capacity=row[4],
                        learning_rate=row[5],
                        social_connections=json.loads(row[6]),
                        current_mood=row[7],
                        story_involvement=row[8],
                    )
                else:
                    # Create default behavior
                    archetype = random.choice(list(self.character_archetypes.keys()))
                    archetype_data = self.character_archetypes[archetype]

                    return NPCBehavior(
                        npc_id=npc_id,
                        personality_traits=archetype_data["personality"].copy(),
                        dialogue_style=archetype_data["dialogue_style"],
                        reaction_patterns={},
                        memory_capacity=10,
                        learning_rate=0.1,
                        social_connections=[],
                        current_mood="neutral",
                        story_involvement=0.5,
                    )
        except Exception as e:
            self.logger.error(f"Failed to load NPC behavior for {npc_id}: {e}")
            return NPCBehavior(
                npc_id=npc_id,
                personality_traits={"neutral": 0.5},
                dialogue_style="generic",
                reaction_patterns={},
                memory_capacity=5,
                learning_rate=0.05,
                social_connections=[],
                current_mood="neutral",
                story_involvement=0.3,
            )

    def _store_npc_behavior(self, behavior: NPCBehavior):
        """Store NPC behavior in database."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """
                INSERT OR REPLACE INTO npc_behaviors 
                (npc_id, personality_traits, dialogue_style, reaction_patterns,
                 memory_capacity, learning_rate, social_connections, current_mood, story_involvement)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
                (
                    behavior.npc_id,
                    json.dumps(behavior.personality_traits),
                    behavior.dialogue_style,
                    json.dumps(behavior.reaction_patterns),
                    behavior.memory_capacity,
                    behavior.learning_rate,
                    json.dumps(behavior.social_connections),
                    behavior.current_mood,
                    behavior.story_involvement,
                ),
            )

    def real_time_player_optimization(self):
        """Perform real-time player experience optimization."""
        try:
            self.logger.info("Performing real-time player experience optimization")

            for player_id, profile in self.player_profiles.items():
                # Check if player needs engagement boost
                if profile.engagement_score < 0.5:
                    self._optimize_player_experience(profile)

        except Exception as e:
            self.logger.error(f"Real-time optimization failed: {e}")

    def _optimize_player_experience(self, profile: PlayerProfile):
        """Optimize experience for individual player."""
        try:
            # Analyze player's recent activity
            with sqlite3.connect(self.db_path) as conn:
                recent_events = conn.execute(
                    """
                    SELECT event_id, satisfaction_score FROM player_interactions 
                    WHERE player_id = ? AND timestamp > datetime('now', '-7 days')
                """,
                    (profile.player_id,),
                ).fetchall()

                if not recent_events:
                    # New or inactive player - generate welcoming content
                    self._generate_welcome_content(profile)
                else:
                    avg_satisfaction = sum(r[1] for r in recent_events) / len(
                        recent_events
                    )

                    if avg_satisfaction < 0.4:
                        # Player is unsatisfied - adjust content difficulty
                        self._adjust_content_difficulty(profile, decrease=True)
                    elif avg_satisfaction > 0.8 and profile.challenge_preference > 0.6:
                        # Player wants more challenge
                        self._adjust_content_difficulty(profile, decrease=False)

        except Exception as e:
            self.logger.error(
                f"Player optimization failed for {profile.player_id}: {e}"
            )

    def _generate_welcome_content(self, profile: PlayerProfile):
        """Generate welcoming content for new/returning players."""
        self.logger.info(f"Generating welcome content for player {profile.name}")

        # Create easy, engaging event
        # This would trigger actual in-game content generation
        pass

    def _adjust_content_difficulty(self, profile: PlayerProfile, decrease: bool):
        """Adjust content difficulty for player."""
        adjustment = "decreased" if decrease else "increased"
        self.logger.info(f"Content difficulty {adjustment} for player {profile.name}")

        # This would affect future event generation for this player
        if decrease:
            profile.challenge_preference = max(0.0, profile.challenge_preference - 0.1)
        else:
            profile.challenge_preference = min(1.0, profile.challenge_preference + 0.1)

    def event_generation_loop(self):
        """Main event generation loop."""
        while self.running:
            try:
                # Generate events periodically
                event = self.generate_dynamic_event()
                if event:
                    self.logger.info(f"Generated event: {event.title}")

                # Clean up expired events
                self._cleanup_expired_events()

                time.sleep(self.config["event_generation_interval"])
            except Exception as e:
                self.logger.error(f"Event generation loop error: {e}")
                time.sleep(60)

    def player_analysis_loop(self):
        """Player analysis and optimization loop."""
        while self.running:
            try:
                self.load_player_profiles()
                self.analyze_player_engagement()
                self.real_time_player_optimization()

                time.sleep(self.config["player_analysis_interval"])
            except Exception as e:
                self.logger.error(f"Player analysis loop error: {e}")
                time.sleep(300)

    def npc_behavior_loop(self):
        """NPC behavior update loop."""
        while self.running:
            try:
                self.update_npc_behaviors()
                time.sleep(self.config["npc_behavior_update_interval"])
            except Exception as e:
                self.logger.error(f"NPC behavior loop error: {e}")
                time.sleep(180)

    def _cleanup_expired_events(self):
        """Clean up expired events."""
        current_time = datetime.now()
        expired_events = []

        for event_id, event in self.active_events.items():
            end_time = event.start_time + timedelta(minutes=event.duration_minutes)
            if current_time > end_time:
                expired_events.append(event_id)

        for event_id in expired_events:
            del self.active_events[event_id]

    def start(self):
        """Start the AI Game Master system."""
        if self.running:
            self.logger.warning("AI Game Master already running")
            return

        self.running = True
        self.logger.info("Starting Advanced AI Game Master - Iteration 13")

        # Load initial data
        self.load_player_profiles()

        # Start processing threads
        threads = [
            threading.Thread(target=self.event_generation_loop),
            threading.Thread(target=self.player_analysis_loop),
            threading.Thread(target=self.npc_behavior_loop),
        ]

        for thread in threads:
            thread.daemon = True
            thread.start()
            self.threads.append(thread)

        self.logger.info("AI Game Master started successfully")

    def stop(self):
        """Stop the AI Game Master system."""
        self.logger.info("Stopping AI Game Master")
        self.running = False

        for thread in self.threads:
            thread.join(timeout=5)

        self.logger.info("AI Game Master stopped")

    def get_status_report(self) -> Dict:
        """Generate status report."""
        return {
            "timestamp": datetime.now().isoformat(),
            "status": "running" if self.running else "stopped",
            "active_events": len(self.active_events),
            "tracked_players": len(self.player_profiles),
            "avg_engagement": (
                sum(p.engagement_score for p in self.player_profiles.values())
                / len(self.player_profiles)
                if self.player_profiles
                else 0
            ),
            "event_types_active": list(
                set(e.event_type.value for e in self.active_events.values())
            ),
            "config": self.config,
        }


def main():
    """Main entry point."""
    gm = AdvancedAIGameMaster()

    try:
        if len(sys.argv) > 1:
            command = sys.argv[1]

            if command == "start":
                gm.start()
                while gm.running:
                    time.sleep(1)
            elif command == "status":
                report = gm.get_status_report()
                print(json.dumps(report, indent=2, default=str))
            else:
                print("Usage: ai_gamemaster.py [start|status]")
        else:
            gm.start()
            print("AI Game Master running. Press Ctrl+C to stop.")
            while gm.running:
                time.sleep(1)

    except KeyboardInterrupt:
        gm.stop()
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
