#!/usr/bin/env python3
"""
Enhanced FFXI Server Launcher with Authentication
Advanced launcher with server-specific branding and authentication system

Features:
- Configurable server name via SERVERNAME environment variable
- User authentication matching web interface
- Server status monitoring and player statistics
- Ashita v4 integration with auto-configuration
- .env file configuration with server information baked in
"""

import os
import sys
import json
import tkinter as tk
from tkinter import ttk, messagebox, filedialog
from pathlib import Path
from typing import Dict, Any, Optional
import subprocess
import configparser
import urllib.request
import urllib.parse
from datetime import datetime
import threading
import logging
import requests
import base64
import hashlib

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class ServerConfig:
    """Manages server configuration with configurable branding"""
    
    def __init__(self, env_file: str = '.env'):
        self.env_file = env_file
        self.config = self.load_env_file()
        self.server_name = self.config.get('SERVERNAME', 'FFXI')
        
    def load_env_file(self) -> Dict[str, str]:
        """Load configuration from .env file"""
        config = {}
        env_path = Path(self.env_file)
        
        if not env_path.exists():
            logger.warning(f"Environment file {self.env_file} not found")
            return self.get_default_config()
        
        try:
            with open(env_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        config[key.strip()] = value.strip().strip('"\'')
        except Exception as e:
            logger.error(f"Failed to load .env file: {e}")
            return self.get_default_config()
        
        return config
    
    def get_default_config(self) -> Dict[str, str]:
        """Get default configuration values"""
        server_name = 'FFXI'
        return {
            'SERVERNAME': server_name,
            f'{server_name}_SERVER_NAME': f'{server_name} Private Server',
            f'{server_name}_SERVER_HOST': 'localhost',
            f'{server_name}_LOGIN_PORT': '54001',
            f'{server_name}_MAP_PORT': '54230',
            f'{server_name}_SEARCH_PORT': '54002',
            f'{server_name}_CLIENT_PATH': '',
            f'{server_name}_WINDOWER_COMPATIBLE': 'true',
            f'{server_name}_ASHITA_COMPATIBLE': 'true',
            f'{server_name}_AUTO_UPDATE': 'true',
            f'{server_name}_CLIENT_TIMEOUT': '30000',
            f'{server_name}_API_SECRET_KEY': 'your_secret_key_here_change_this',
            f'{server_name}_ADMIN_USERNAME': 'admin',
            f'{server_name}_ADMIN_PASSWORD': 'admin123'
        }
    
    def get(self, key: str, default: str = '') -> str:
        """Get configuration value with server name prefix"""
        # Try with server name prefix first
        prefixed_key = f"{self.server_name}_{key}"
        if prefixed_key in self.config:
            return self.config[prefixed_key]
        
        # Fallback to original key
        return self.config.get(key, default)
    
    def set(self, key: str, value: str):
        """Set configuration value with server name prefix"""
        prefixed_key = f"{self.server_name}_{key}"
        self.config[prefixed_key] = value
    
    def save(self):
        """Save configuration back to .env file"""
        try:
            with open(self.env_file, 'w') as f:
                f.write(f"# {self.server_name} Server Configuration\n")
                f.write(f"# Generated by {self.server_name} Launcher on {datetime.now().isoformat()}\n\n")
                
                # Write SERVERNAME first
                f.write(f"SERVERNAME={self.server_name}\n\n")
                
                for key, value in sorted(self.config.items()):
                    if key != 'SERVERNAME':  # Skip SERVERNAME as it's already written
                        f.write(f"{key}={value}\n")
        except Exception as e:
            logger.error(f"Failed to save .env file: {e}")

class ServerAPIClient:
    """Client for communicating with server API"""
    
    def __init__(self, server_config: ServerConfig):
        self.config = server_config
        self.server_name = server_config.server_name
        self.base_url = f"http://{self.config.get('SERVER_HOST', 'localhost')}:5000"
        self.token = None
        
    def authenticate(self, username: str, password: str) -> Dict[str, Any]:
        """Authenticate with server API"""
        try:
            response = requests.post(
                f"{self.base_url}/auth/token",
                json={'username': username, 'password': password},
                timeout=10
            )
            
            if response.status_code == 200:
                data = response.json()
                self.token = data.get('token')
                return {'success': True, 'data': data}
            else:
                return {'success': False, 'error': response.json().get('error', 'Authentication failed')}
                
        except requests.exceptions.RequestException as e:
            return {'success': False, 'error': f'Connection failed: {str(e)}'}
    
    def get_server_status(self) -> Dict[str, Any]:
        """Get server status information"""
        if not self.token:
            return {'success': False, 'error': 'Not authenticated'}
        
        try:
            headers = {'Authorization': f'Bearer {self.token}'}
            response = requests.get(f"{self.base_url}/api/status", headers=headers, timeout=10)
            
            if response.status_code == 200:
                return {'success': True, 'data': response.json()}
            else:
                return {'success': False, 'error': 'Failed to get server status'}
                
        except requests.exceptions.RequestException as e:
            return {'success': False, 'error': f'Connection failed: {str(e)}'}
    
    def get_player_info(self) -> Dict[str, Any]:
        """Get player information (placeholder for future implementation)"""
        if not self.token:
            return {'success': False, 'error': 'Not authenticated'}
        
        # This would connect to actual player database
        return {
            'success': True, 
            'data': {
                'online_players': 42,
                'max_players': int(self.config.get('MAX_PLAYERS', '500')),
                'server_uptime': '2 days, 14 hours',
                'server_version': '1.0.0'
            }
        }

class AshitaConfigGenerator:
    """Generates Ashita v4 configuration files with server branding"""
    
    def __init__(self, server_config: ServerConfig):
        self.server_config = server_config
        self.server_name = server_config.server_name
    
    def generate_config(self, output_path: str) -> bool:
        """Generate Ashita configuration file"""
        try:
            config = configparser.ConfigParser()
            
            # Ashita launcher section with server branding
            config['ashita.launcher'] = {
                'autoclose': '1',
                'name': self.server_config.get('SERVER_NAME', f'{self.server_name} Server')
            }
            
            # Boot configuration
            config['ashita.boot'] = {
                'file': '.\\bootloader\\pol.exe',
                'command': f"--server {self.server_config.get('SERVER_HOST', 'localhost')}",
                'gamemodule': 'ffximain.dll',
                'script': 'default.txt',
                'args': ''
            }
            
            # Font configuration
            config['ashita.fonts'] = {
                'd3d8.disable_scaling': '0',
                'd3d8.family': 'Arial',
                'd3d8.height': '10'
            }
            
            # Input configuration
            config['ashita.input'] = {
                'gamepad.allowbackground': '0',
                'gamepad.disableenumeration': '0',
                'keyboard.blockinput': '0',
                'keyboard.blockbindsduringinput': '1',
                'keyboard.silentbinds': '0',
                'keyboard.windowskeyenabled': '0',
                'mouse.blockinput': '0',
                'mouse.unhook': '1'
            }
            
            # Language configuration
            config['ashita.language'] = {
                'playonline': '2',
                'ashita': '2'
            }
            
            # Logging configuration
            config['ashita.logging'] = {
                'level': '5',
                'crashdumps': '1'
            }
            
            # Miscellaneous settings
            config['ashita.misc'] = {
                'addons.silent': '0',
                'aliases.silent': '0',
                'plugins.silent': '0'
            }
            
            # POL plugins configuration
            config['ashita.polplugins'] = {
                'sandbox': '0'
            }
            
            # Resources configuration
            config['ashita.resources'] = {
                'offsets.use_overrides': '1',
                'pointers.use_overrides': '1',
                'resources.use_overrides': '1'
            }
            
            # Task pool configuration
            config['ashita.taskpool'] = {
                'threadcount': '-1'
            }
            
            # Window start position
            config['ashita.window.startpos'] = {
                'x': '-1',
                'y': '-1'
            }
            
            # FFXI Direct3D8 settings
            config['ffxi.direct3d8'] = {
                'presentparams.backbufferformat': '-1',
                'presentparams.backbuffercount': '-1',
                'presentparams.multisampletype': '-1',
                'presentparams.swapeffect': '-1',
                'presentparams.enableautodepthstencil': '-1',
                'presentparams.autodepthstencilformat': '-1',
                'presentparams.flags': '-1',
                'presentparams.fullscreen_refreshrateinhz': '-1',
                'presentparams.fullscreen_presentationinterval': '-1',
                'behaviorflags.fpu_preserve': '0'
            }
            
            # FFXI registry settings (default windowed mode)
            config['ffxi.registry'] = {
                '0000': '6',  # Window mode
                '0001': '1920',  # Screen width
                '0002': '1080',  # Screen height
                '0003': '4096',  # Buffer width
                '0004': '4096',  # Buffer height
                '0017': '0',  # Fullscreen mode (0 = windowed)
                '0042': self.server_config.get('CLIENT_PATH', 'C:\\Program Files (x86)\\SquareEnix\\FINAL FANTASY XI'),
                '0043': '1',
                '0044': '1',
                '0045': '0'
            }
            
            # Write configuration file
            with open(output_path, 'w') as f:
                # Custom header format for Ashita with server branding
                f.write(";---------------------------------------------------------------------------------------------------\n")
                f.write(f"; {self.server_name} Server Launcher Configuration\n")
                f.write(f"; Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"; Server: {self.server_config.get('SERVER_NAME')}\n")
                f.write(f"; Host: {self.server_config.get('SERVER_HOST')}\n")
                f.write(";---------------------------------------------------------------------------------------------------\n\n")
                
                # Write each section
                for section_name in config.sections():
                    f.write(f"[{section_name}]\n")
                    for key, value in config[section_name].items():
                        f.write(f"{key} = {value}\n")
                    f.write("\n")
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to generate Ashita config: {e}")
            return False

class EnhancedLauncherGUI:
    """Enhanced GUI interface with authentication and server branding"""
    
    def __init__(self):
        self.server_config = ServerConfig()
        self.server_name = self.server_config.server_name
        self.api_client = ServerAPIClient(self.server_config)
        self.ashita_generator = AshitaConfigGenerator(self.server_config)
        
        self.root = tk.Tk()
        self.root.title(f"{self.server_name} Server Launcher")
        self.root.geometry("900x700")
        self.root.resizable(True, True)
        
        # Configure style
        style = ttk.Style()
        style.theme_use('clam')
        
        self.authenticated = False
        self.user_info = None
        
        self.create_widgets()
        self.show_login_screen()
    
    def create_widgets(self):
        """Create GUI widgets"""
        # Main container
        self.main_container = ttk.Frame(self.root)
        self.main_container.pack(fill=tk.BOTH, expand=True)
        
        # Login frame (initially visible)
        self.login_frame = ttk.Frame(self.main_container)
        self.create_login_widgets()
        
        # Main application frame (initially hidden)
        self.app_frame = ttk.Frame(self.main_container)
        self.create_app_widgets()
    
    def create_login_widgets(self):
        """Create login interface"""
        self.login_frame.pack(fill=tk.BOTH, expand=True)
        
        # Center the login form
        login_container = ttk.Frame(self.login_frame)
        login_container.place(relx=0.5, rely=0.5, anchor=tk.CENTER)
        
        # Server branding
        ttk.Label(login_container, text=f"{self.server_name} Server", 
                 font=('Arial', 20, 'bold')).pack(pady=20)
        ttk.Label(login_container, text="Launcher Authentication", 
                 font=('Arial', 12)).pack(pady=5)
        
        # Login form
        login_form = ttk.LabelFrame(login_container, text="Login Credentials", padding=20)
        login_form.pack(pady=20, padx=40, fill=tk.X)
        
        # Username
        ttk.Label(login_form, text="Username:").pack(anchor=tk.W)
        self.username_var = tk.StringVar()
        self.username_entry = ttk.Entry(login_form, textvariable=self.username_var, width=30)
        self.username_entry.pack(pady=5, fill=tk.X)
        
        # Password
        ttk.Label(login_form, text="Password:").pack(anchor=tk.W, pady=(10, 0))
        self.password_var = tk.StringVar()
        self.password_entry = ttk.Entry(login_form, textvariable=self.password_var, show='*', width=30)
        self.password_entry.pack(pady=5, fill=tk.X)
        
        # Login button
        self.login_button = ttk.Button(login_form, text="Login", command=self.login)
        self.login_button.pack(pady=15)
        
        # Status label
        self.login_status_label = ttk.Label(login_form, text="", foreground='red')
        self.login_status_label.pack()
        
        # Server info
        server_info = ttk.LabelFrame(login_container, text="Server Information", padding=15)
        server_info.pack(pady=10, padx=40, fill=tk.X)
        
        ttk.Label(server_info, text=f"Server: {self.server_config.get('SERVER_NAME')}").pack(anchor=tk.W)
        ttk.Label(server_info, text=f"Host: {self.server_config.get('SERVER_HOST')}").pack(anchor=tk.W)
        ttk.Label(server_info, text=f"Login Port: {self.server_config.get('LOGIN_PORT')}").pack(anchor=tk.W)
        
        # Bind Enter key to login
        self.username_entry.bind('<Return>', lambda e: self.password_entry.focus())
        self.password_entry.bind('<Return>', lambda e: self.login())
    
    def create_app_widgets(self):
        """Create main application interface"""
        # Header with server info and logout
        header_frame = ttk.Frame(self.app_frame)
        header_frame.pack(fill=tk.X, padx=10, pady=5)
        
        ttk.Label(header_frame, text=f"{self.server_name} Server Dashboard", 
                 font=('Arial', 16, 'bold')).pack(side=tk.LEFT)
        
        ttk.Button(header_frame, text="Logout", command=self.logout).pack(side=tk.RIGHT)
        
        # Create notebook for tabs
        self.notebook = ttk.Notebook(self.app_frame)
        self.notebook.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)
        
        # Server Status Tab
        self.create_status_tab()
        
        # Server Configuration Tab
        self.create_server_tab()
        
        # Client Configuration Tab
        self.create_client_tab()
        
        # Advanced Settings Tab
        self.create_advanced_tab()
        
        # Launcher Tab
        self.create_launcher_tab()
    
    def create_status_tab(self):
        """Create server status tab"""
        frame = ttk.Frame(self.notebook)
        self.notebook.add(frame, text="Server Status")
        
        ttk.Label(frame, text="Server Status Dashboard", font=('Arial', 12, 'bold')).pack(pady=10)
        
        # Status information frame
        self.status_info_frame = ttk.LabelFrame(frame, text="Current Status")
        self.status_info_frame.pack(fill=tk.X, padx=20, pady=10)
        
        # Create status labels (will be updated by refresh_status)
        self.status_labels = {}
        
        # Refresh button
        ttk.Button(frame, text="Refresh Status", command=self.refresh_status).pack(pady=10)
        
        # Auto-refresh status every 30 seconds
        self.auto_refresh_status()
    
    def create_server_tab(self):
        """Create server configuration tab"""
        frame = ttk.Frame(self.notebook)
        self.notebook.add(frame, text="Server Settings")
        
        # Server settings
        ttk.Label(frame, text="Server Configuration", font=('Arial', 12, 'bold')).pack(pady=10)
        
        # Server name
        ttk.Label(frame, text="Server Name:").pack(anchor=tk.W, padx=20)
        self.server_name_var = tk.StringVar()
        ttk.Entry(frame, textvariable=self.server_name_var, width=50).pack(padx=20, pady=5)
        
        # Server host
        ttk.Label(frame, text="Server Host:").pack(anchor=tk.W, padx=20)
        self.server_host_var = tk.StringVar()
        ttk.Entry(frame, textvariable=self.server_host_var, width=50).pack(padx=20, pady=5)
        
        # Port configuration frame
        port_frame = ttk.LabelFrame(frame, text="Port Configuration")
        port_frame.pack(fill=tk.X, padx=20, pady=10)
        
        # Login port
        ttk.Label(port_frame, text="Login Port:").grid(row=0, column=0, sticky=tk.W, padx=5, pady=5)
        self.login_port_var = tk.StringVar()
        ttk.Entry(port_frame, textvariable=self.login_port_var, width=10).grid(row=0, column=1, padx=5, pady=5)
        
        # Map port
        ttk.Label(port_frame, text="Map Port:").grid(row=0, column=2, sticky=tk.W, padx=5, pady=5)
        self.map_port_var = tk.StringVar()
        ttk.Entry(port_frame, textvariable=self.map_port_var, width=10).grid(row=0, column=3, padx=5, pady=5)
        
        # Search port
        ttk.Label(port_frame, text="Search Port:").grid(row=1, column=0, sticky=tk.W, padx=5, pady=5)
        self.search_port_var = tk.StringVar()
        ttk.Entry(port_frame, textvariable=self.search_port_var, width=10).grid(row=1, column=1, padx=5, pady=5)
    
    def create_client_tab(self):
        """Create client configuration tab"""
        frame = ttk.Frame(self.notebook)
        self.notebook.add(frame, text="Client Settings")
        
        ttk.Label(frame, text="Client Configuration", font=('Arial', 12, 'bold')).pack(pady=10)
        
        # Client path
        ttk.Label(frame, text=f"{self.server_name} Client Path:").pack(anchor=tk.W, padx=20)
        client_path_frame = ttk.Frame(frame)
        client_path_frame.pack(fill=tk.X, padx=20, pady=5)
        
        self.client_path_var = tk.StringVar()
        ttk.Entry(client_path_frame, textvariable=self.client_path_var, width=60).pack(side=tk.LEFT, fill=tk.X, expand=True)
        ttk.Button(client_path_frame, text="Browse", command=self.browse_client_path).pack(side=tk.RIGHT, padx=(5, 0))
        
        # Compatibility options
        compat_frame = ttk.LabelFrame(frame, text="Client Compatibility")
        compat_frame.pack(fill=tk.X, padx=20, pady=10)
        
        self.windower_compat_var = tk.BooleanVar()
        ttk.Checkbutton(compat_frame, text="Windower Compatible", variable=self.windower_compat_var).pack(anchor=tk.W, padx=5, pady=2)
        
        self.ashita_compat_var = tk.BooleanVar()
        ttk.Checkbutton(compat_frame, text="Ashita Compatible", variable=self.ashita_compat_var).pack(anchor=tk.W, padx=5, pady=2)
        
        self.auto_update_var = tk.BooleanVar()
        ttk.Checkbutton(compat_frame, text="Auto Update Client", variable=self.auto_update_var).pack(anchor=tk.W, padx=5, pady=2)
    
    def create_advanced_tab(self):
        """Create advanced settings tab"""
        frame = ttk.Frame(self.notebook)
        self.notebook.add(frame, text="Advanced")
        
        ttk.Label(frame, text="Advanced Settings", font=('Arial', 12, 'bold')).pack(pady=10)
        
        # Timeout settings
        timeout_frame = ttk.LabelFrame(frame, text="Timeout Settings")
        timeout_frame.pack(fill=tk.X, padx=20, pady=10)
        
        ttk.Label(timeout_frame, text="Client Timeout (ms):").grid(row=0, column=0, sticky=tk.W, padx=5, pady=5)
        self.client_timeout_var = tk.StringVar()
        ttk.Entry(timeout_frame, textvariable=self.client_timeout_var, width=10).grid(row=0, column=1, padx=5, pady=5)
        
        # Configuration files
        config_frame = ttk.LabelFrame(frame, text="Configuration Files")
        config_frame.pack(fill=tk.X, padx=20, pady=10)
        
        ttk.Button(config_frame, text="Load .env File", command=self.load_env_file).pack(side=tk.LEFT, padx=5, pady=5)
        ttk.Button(config_frame, text="Save .env File", command=self.save_env_file).pack(side=tk.LEFT, padx=5, pady=5)
        ttk.Button(config_frame, text="Export Ashita Config", command=self.export_ashita_config).pack(side=tk.LEFT, padx=5, pady=5)
    
    def create_launcher_tab(self):
        """Create launcher tab"""
        frame = ttk.Frame(self.notebook)
        self.notebook.add(frame, text="Launch Client")
        
        ttk.Label(frame, text=f"Launch {self.server_name} Client", font=('Arial', 12, 'bold')).pack(pady=10)
        
        # Status display
        self.status_text = tk.Text(frame, height=15, width=80)
        self.status_text.pack(padx=20, pady=10, fill=tk.BOTH, expand=True)
        
        # Scrollbar for status text
        scrollbar = ttk.Scrollbar(self.status_text)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self.status_text.config(yscrollcommand=scrollbar.set)
        scrollbar.config(command=self.status_text.yview)
        
        # Buttons
        button_frame = ttk.Frame(frame)
        button_frame.pack(pady=10)
        
        ttk.Button(button_frame, text="Check Server Status", command=self.check_server_status).pack(side=tk.LEFT, padx=5)
        ttk.Button(button_frame, text="Launch Client", command=self.launch_client).pack(side=tk.LEFT, padx=5)
        ttk.Button(button_frame, text="Clear Log", command=self.clear_log).pack(side=tk.LEFT, padx=5)
    
    def show_login_screen(self):
        """Show login screen"""
        self.app_frame.pack_forget()
        self.login_frame.pack(fill=tk.BOTH, expand=True)
        self.username_entry.focus()
    
    def show_main_app(self):
        """Show main application"""
        self.login_frame.pack_forget()
        self.app_frame.pack(fill=tk.BOTH, expand=True)
        self.load_current_config()
    
    def login(self):
        """Handle user login"""
        username = self.username_var.get().strip()
        password = self.password_var.get().strip()
        
        if not username or not password:
            self.login_status_label.config(text="Please enter username and password")
            return
        
        self.login_button.config(state='disabled')
        self.login_status_label.config(text="Authenticating...", foreground='blue')
        
        def authenticate():
            result = self.api_client.authenticate(username, password)
            
            self.root.after(0, lambda: self.handle_login_result(result))
        
        threading.Thread(target=authenticate, daemon=True).start()
    
    def handle_login_result(self, result: Dict[str, Any]):
        """Handle authentication result"""
        self.login_button.config(state='normal')
        
        if result['success']:
            self.authenticated = True
            self.user_info = result['data']
            self.login_status_label.config(text="Login successful!", foreground='green')
            self.root.after(1000, self.show_main_app)  # Show main app after 1 second
        else:
            self.login_status_label.config(text=f"Login failed: {result['error']}", foreground='red')
    
    def logout(self):
        """Handle user logout"""
        self.authenticated = False
        self.user_info = None
        self.api_client.token = None
        self.username_var.set("")
        self.password_var.set("")
        self.login_status_label.config(text="")
        self.show_login_screen()
    
    def refresh_status(self):
        """Refresh server status information"""
        if not self.authenticated:
            return
        
        def get_status():
            status_result = self.api_client.get_server_status()
            player_result = self.api_client.get_player_info()
            
            self.root.after(0, lambda: self.update_status_display(status_result, player_result))
        
        threading.Thread(target=get_status, daemon=True).start()
    
    def update_status_display(self, status_result: Dict[str, Any], player_result: Dict[str, Any]):
        """Update status display with server information"""
        # Clear existing status labels
        for widget in self.status_info_frame.winfo_children():
            widget.destroy()
        
        if status_result['success']:
            status_data = status_result['data']
            
            ttk.Label(self.status_info_frame, text=f"Server Status: Online", foreground='green').pack(anchor=tk.W, padx=5)
            ttk.Label(self.status_info_frame, text=f"Database: {status_data.get('database', {}).get('status', 'Unknown')}").pack(anchor=tk.W, padx=5)
            
        else:
            ttk.Label(self.status_info_frame, text=f"Server Status: {status_result['error']}", foreground='red').pack(anchor=tk.W, padx=5)
        
        if player_result['success']:
            player_data = player_result['data']
            
            ttk.Label(self.status_info_frame, text=f"Online Players: {player_data['online_players']}/{player_data['max_players']}").pack(anchor=tk.W, padx=5)
            ttk.Label(self.status_info_frame, text=f"Server Uptime: {player_data['server_uptime']}").pack(anchor=tk.W, padx=5)
            ttk.Label(self.status_info_frame, text=f"Version: {player_data['server_version']}").pack(anchor=tk.W, padx=5)
    
    def auto_refresh_status(self):
        """Auto-refresh status every 30 seconds"""
        if self.authenticated:
            self.refresh_status()
        
        # Schedule next refresh
        self.root.after(30000, self.auto_refresh_status)  # 30 seconds
    
    def load_current_config(self):
        """Load current configuration into GUI"""
        self.server_name_var.set(self.server_config.get('SERVER_NAME'))
        self.server_host_var.set(self.server_config.get('SERVER_HOST'))
        self.login_port_var.set(self.server_config.get('LOGIN_PORT'))
        self.map_port_var.set(self.server_config.get('MAP_PORT'))
        self.search_port_var.set(self.server_config.get('SEARCH_PORT'))
        self.client_path_var.set(self.server_config.get('CLIENT_PATH'))
        self.client_timeout_var.set(self.server_config.get('CLIENT_TIMEOUT'))
        
        self.windower_compat_var.set(self.server_config.get('WINDOWER_COMPATIBLE').lower() == 'true')
        self.ashita_compat_var.set(self.server_config.get('ASHITA_COMPATIBLE').lower() == 'true')
        self.auto_update_var.set(self.server_config.get('AUTO_UPDATE').lower() == 'true')
    
    def save_current_config(self):
        """Save current GUI configuration"""
        self.server_config.set('SERVER_NAME', self.server_name_var.get())
        self.server_config.set('SERVER_HOST', self.server_host_var.get())
        self.server_config.set('LOGIN_PORT', self.login_port_var.get())
        self.server_config.set('MAP_PORT', self.map_port_var.get())
        self.server_config.set('SEARCH_PORT', self.search_port_var.get())
        self.server_config.set('CLIENT_PATH', self.client_path_var.get())
        self.server_config.set('CLIENT_TIMEOUT', self.client_timeout_var.get())
        
        self.server_config.set('WINDOWER_COMPATIBLE', str(self.windower_compat_var.get()).lower())
        self.server_config.set('ASHITA_COMPATIBLE', str(self.ashita_compat_var.get()).lower())
        self.server_config.set('AUTO_UPDATE', str(self.auto_update_var.get()).lower())
    
    def browse_client_path(self):
        """Browse for client path"""
        path = filedialog.askdirectory(title=f"Select {self.server_name} Client Directory")
        if path:
            self.client_path_var.set(path)
    
    def load_env_file(self):
        """Load configuration from .env file"""
        file_path = filedialog.askopenfilename(
            title="Select .env file",
            filetypes=[("Environment files", "*.env"), ("All files", "*.*")]
        )
        if file_path:
            self.server_config = ServerConfig(file_path)
            self.ashita_generator = AshitaConfigGenerator(self.server_config)
            self.load_current_config()
            self.log_message(f"Loaded configuration from {file_path}")
    
    def save_env_file(self):
        """Save configuration to .env file"""
        file_path = filedialog.asksaveasfilename(
            title="Save .env file",
            defaultextension=".env",
            filetypes=[("Environment files", "*.env"), ("All files", "*.*")]
        )
        if file_path:
            self.save_current_config()
            self.server_config.env_file = file_path
            self.server_config.save()
            self.log_message(f"Saved configuration to {file_path}")
    
    def export_ashita_config(self):
        """Export Ashita configuration file"""
        file_path = filedialog.asksaveasfilename(
            title="Export Ashita configuration",
            defaultextension=".ini",
            filetypes=[("INI files", "*.ini"), ("All files", "*.*")]
        )
        if file_path:
            self.save_current_config()
            if self.ashita_generator.generate_config(file_path):
                self.log_message(f"Exported Ashita configuration to {file_path}")
                messagebox.showinfo("Success", f"Ashita configuration exported to {file_path}")
            else:
                self.log_message("Failed to export Ashita configuration")
                messagebox.showerror("Error", "Failed to export Ashita configuration")
    
    def check_server_status(self):
        """Check server status"""
        def check_status():
            self.log_message("Checking server status...")
            
            host = self.server_host_var.get() or 'localhost'
            login_port = self.login_port_var.get() or '54001'
            
            try:
                import socket
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(5)
                result = sock.connect_ex((host, int(login_port)))
                sock.close()
                
                if result == 0:
                    self.log_message(f"✅ Server is online at {host}:{login_port}")
                else:
                    self.log_message(f"❌ Server is offline or unreachable at {host}:{login_port}")
            except Exception as e:
                self.log_message(f"❌ Failed to check server status: {e}")
        
        threading.Thread(target=check_status, daemon=True).start()
    
    def launch_client(self):
        """Launch client with Ashita"""
        def launch():
            self.log_message(f"Preparing to launch {self.server_name} client...")
            
            # Save current configuration
            self.save_current_config()
            
            # Generate temporary Ashita config
            temp_config_path = "temp_ashita_config.ini"
            if not self.ashita_generator.generate_config(temp_config_path):
                self.log_message("❌ Failed to generate Ashita configuration")
                return
            
            self.log_message("✅ Generated Ashita configuration")
            
            # Check for Ashita CLI
            ashita_cli_path = Path("ashita/Ashita-cli.exe")
            if not ashita_cli_path.exists():
                self.log_message("❌ Ashita CLI not found. Please ensure Ashita files are downloaded.")
                return
            
            try:
                # Launch Ashita with generated configuration
                cmd = [str(ashita_cli_path), "--config", temp_config_path]
                self.log_message(f"Launching: {' '.join(cmd)}")
                
                process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
                
                # Read output
                stdout, stderr = process.communicate(timeout=30)
                
                if process.returncode == 0:
                    self.log_message("✅ Client launched successfully")
                    if stdout:
                        self.log_message(f"Output: {stdout}")
                else:
                    self.log_message(f"❌ Client launch failed (exit code: {process.returncode})")
                    if stderr:
                        self.log_message(f"Error: {stderr}")
                
            except subprocess.TimeoutExpired:
                self.log_message("⚠️ Launch command timed out (this may be normal)")
            except Exception as e:
                self.log_message(f"❌ Failed to launch client: {e}")
            finally:
                # Clean up temporary config
                if Path(temp_config_path).exists():
                    Path(temp_config_path).unlink()
        
        threading.Thread(target=launch, daemon=True).start()
    
    def log_message(self, message: str):
        """Add message to status log"""
        timestamp = datetime.now().strftime("%H:%M:%S")
        formatted_message = f"[{timestamp}] {message}\n"
        
        self.status_text.insert(tk.END, formatted_message)
        self.status_text.see(tk.END)
        self.root.update()
    
    def clear_log(self):
        """Clear the status log"""
        self.status_text.delete(1.0, tk.END)
    
    def run(self):
        """Run the GUI"""
        self.root.mainloop()

def main():
    """Main entry point"""
    if len(sys.argv) > 1:
        # CLI mode
        if sys.argv[1] == '--generate-config':
            env_file = sys.argv[2] if len(sys.argv) > 2 else '.env'
            output_file = sys.argv[3] if len(sys.argv) > 3 else 'ashita_config.ini'
            
            config = ServerConfig(env_file)
            generator = AshitaConfigGenerator(config)
            
            if generator.generate_config(output_file):
                print(f"✅ Generated Ashita configuration: {output_file}")
                print(f"Server: {config.get('SERVER_NAME')}")
                print(f"Host: {config.get('SERVER_HOST')}")
            else:
                print("❌ Failed to generate configuration")
                sys.exit(1)
        
        elif sys.argv[1] == '--check-server':
            env_file = sys.argv[2] if len(sys.argv) > 2 else '.env'
            config = ServerConfig(env_file)
            
            import socket
            host = config.get('SERVER_HOST', 'localhost')
            port = int(config.get('LOGIN_PORT', '54001'))
            
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(5)
                result = sock.connect_ex((host, port))
                sock.close()
                
                if result == 0:
                    print(f"✅ Server is online at {host}:{port}")
                else:
                    print(f"❌ Server is offline or unreachable at {host}:{port}")
                    sys.exit(1)
            except Exception as e:
                print(f"❌ Failed to check server: {e}")
                sys.exit(1)
        
        else:
            config = ServerConfig()
            server_name = config.server_name
            print(f"{server_name} Server Launcher")
            print("Usage:")
            print(f"  python enhanced_{server_name.lower()}_launcher.py                           - Launch GUI")
            print(f"  python enhanced_{server_name.lower()}_launcher.py --generate-config [env] [out] - Generate Ashita config")
            print(f"  python enhanced_{server_name.lower()}_launcher.py --check-server [env]      - Check server status")
    
    else:
        # GUI mode
        app = EnhancedLauncherGUI()
        app.run()

if __name__ == "__main__":
    main()