#!/usr/bin/env python3
"""
FFXI Server Launcher
Advanced launcher for FFXI server with Ashita v4 integration and .env configuration support

Features:
- Reads server configuration from .env files
- Generates Ashita-compatible configuration files
- Supports both retail and private server setups
- Automatic client validation and update checking
- GUI and CLI interfaces
"""

import os
import sys
import json
import tkinter as tk
from tkinter import ttk, messagebox, filedialog
from pathlib import Path
from typing import Dict, Any, Optional
import subprocess
import configparser
import urllib.request
import urllib.parse
from datetime import datetime
import threading
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class FFXIServerConfig:
    """Manages FFXI server configuration from .env files"""
    
    def __init__(self, env_file: str = '.env'):
        self.env_file = env_file
        self.config = self.load_env_file()
    
    def load_env_file(self) -> Dict[str, str]:
        """Load configuration from .env file"""
        config = {}
        env_path = Path(self.env_file)
        
        if not env_path.exists():
            logger.warning(f"Environment file {self.env_file} not found")
            return self.get_default_config()
        
        try:
            with open(env_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        config[key.strip()] = value.strip().strip('"\'')
        except Exception as e:
            logger.error(f"Failed to load .env file: {e}")
            return self.get_default_config()
        
        return config
    
    def get_default_config(self) -> Dict[str, str]:
        """Get default configuration values"""
        return {
            'FFXI_SERVER_NAME': 'FFXI Private Server',
            'FFXI_SERVER_HOST': 'localhost',
            'FFXI_LOGIN_PORT': '54001',
            'FFXI_MAP_PORT': '54230',
            'FFXI_SEARCH_PORT': '54002',
            'FFXI_CLIENT_PATH': '',
            'FFXI_WINDOWER_COMPATIBLE': 'true',
            'FFXI_ASHITA_COMPATIBLE': 'true',
            'FFXI_AUTO_UPDATE': 'true',
            'FFXI_CLIENT_TIMEOUT': '30000'
        }
    
    def get(self, key: str, default: str = '') -> str:
        """Get configuration value"""
        return self.config.get(key, default)
    
    def set(self, key: str, value: str):
        """Set configuration value"""
        self.config[key] = value
    
    def save(self):
        """Save configuration back to .env file"""
        try:
            with open(self.env_file, 'w') as f:
                f.write("# FFXI Server Configuration\n")
                f.write(f"# Generated by FFXI Launcher on {datetime.now().isoformat()}\n\n")
                
                for key, value in sorted(self.config.items()):
                    f.write(f"{key}={value}\n")
        except Exception as e:
            logger.error(f"Failed to save .env file: {e}")

class AshitaConfigGenerator:
    """Generates Ashita v4 configuration files"""
    
    def __init__(self, server_config: FFXIServerConfig):
        self.server_config = server_config
    
    def generate_config(self, output_path: str) -> bool:
        """Generate Ashita configuration file"""
        try:
            config = configparser.ConfigParser()
            
            # Ashita launcher section
            config['ashita.launcher'] = {
                'autoclose': '1',
                'name': self.server_config.get('FFXI_SERVER_NAME', 'FFXI Server')
            }
            
            # Boot configuration
            config['ashita.boot'] = {
                'file': '.\\bootloader\\pol.exe',
                'command': f"--server {self.server_config.get('FFXI_SERVER_HOST', 'localhost')}",
                'gamemodule': 'ffximain.dll',
                'script': 'default.txt',
                'args': ''
            }
            
            # Font configuration
            config['ashita.fonts'] = {
                'd3d8.disable_scaling': '0',
                'd3d8.family': 'Arial',
                'd3d8.height': '10'
            }
            
            # Input configuration
            config['ashita.input'] = {
                'gamepad.allowbackground': '0',
                'gamepad.disableenumeration': '0',
                'keyboard.blockinput': '0',
                'keyboard.blockbindsduringinput': '1',
                'keyboard.silentbinds': '0',
                'keyboard.windowskeyenabled': '0',
                'mouse.blockinput': '0',
                'mouse.unhook': '1'
            }
            
            # Language configuration
            config['ashita.language'] = {
                'playonline': '2',
                'ashita': '2'
            }
            
            # Logging configuration
            config['ashita.logging'] = {
                'level': '5',
                'crashdumps': '1'
            }
            
            # Miscellaneous settings
            config['ashita.misc'] = {
                'addons.silent': '0',
                'aliases.silent': '0',
                'plugins.silent': '0'
            }
            
            # POL plugins configuration
            config['ashita.polplugins'] = {
                'sandbox': '0'
            }
            
            # Resources configuration
            config['ashita.resources'] = {
                'offsets.use_overrides': '1',
                'pointers.use_overrides': '1',
                'resources.use_overrides': '1'
            }
            
            # Task pool configuration
            config['ashita.taskpool'] = {
                'threadcount': '-1'
            }
            
            # Window start position
            config['ashita.window.startpos'] = {
                'x': '-1',
                'y': '-1'
            }
            
            # FFXI Direct3D8 settings
            config['ffxi.direct3d8'] = {
                'presentparams.backbufferformat': '-1',
                'presentparams.backbuffercount': '-1',
                'presentparams.multisampletype': '-1',
                'presentparams.swapeffect': '-1',
                'presentparams.enableautodepthstencil': '-1',
                'presentparams.autodepthstencilformat': '-1',
                'presentparams.flags': '-1',
                'presentparams.fullscreen_refreshrateinhz': '-1',
                'presentparams.fullscreen_presentationinterval': '-1',
                'behaviorflags.fpu_preserve': '0'
            }
            
            # FFXI registry settings (default windowed mode)
            config['ffxi.registry'] = {
                '0000': '6',  # Window mode
                '0001': '1920',  # Screen width
                '0002': '1080',  # Screen height
                '0003': '4096',  # Buffer width
                '0004': '4096',  # Buffer height
                '0017': '0',  # Fullscreen mode (0 = windowed)
                '0042': self.server_config.get('FFXI_CLIENT_PATH', 'C:\\Program Files (x86)\\SquareEnix\\FINAL FANTASY XI'),
                '0043': '1',
                '0044': '1',
                '0045': '0'
            }
            
            # Write configuration file
            with open(output_path, 'w') as f:
                # Custom header format for Ashita
                f.write(";---------------------------------------------------------------------------------------------------\n")
                f.write("; FFXI Server Launcher Configuration\n")
                f.write(f"; Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"; Server: {self.server_config.get('FFXI_SERVER_NAME')}\n")
                f.write(f"; Host: {self.server_config.get('FFXI_SERVER_HOST')}\n")
                f.write(";---------------------------------------------------------------------------------------------------\n\n")
                
                # Write each section
                for section_name in config.sections():
                    f.write(f"[{section_name}]\n")
                    for key, value in config[section_name].items():
                        f.write(f"{key} = {value}\n")
                    f.write("\n")
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to generate Ashita config: {e}")
            return False

class FFXILauncherGUI:
    """GUI interface for FFXI Launcher"""
    
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("FFXI Server Launcher")
        self.root.geometry("800x600")
        self.root.resizable(True, True)
        
        # Configure style
        style = ttk.Style()
        style.theme_use('clam')
        
        self.server_config = FFXIServerConfig()
        self.ashita_generator = AshitaConfigGenerator(self.server_config)
        
        self.create_widgets()
        self.load_current_config()
    
    def create_widgets(self):
        """Create GUI widgets"""
        # Create notebook for tabs
        notebook = ttk.Notebook(self.root)
        notebook.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)
        
        # Server Configuration Tab
        self.create_server_tab(notebook)
        
        # Client Configuration Tab
        self.create_client_tab(notebook)
        
        # Advanced Settings Tab
        self.create_advanced_tab(notebook)
        
        # Launcher Tab
        self.create_launcher_tab(notebook)
    
    def create_server_tab(self, notebook):
        """Create server configuration tab"""
        frame = ttk.Frame(notebook)
        notebook.add(frame, text="Server Settings")
        
        # Server settings
        ttk.Label(frame, text="Server Configuration", font=('Arial', 12, 'bold')).pack(pady=10)
        
        # Server name
        ttk.Label(frame, text="Server Name:").pack(anchor=tk.W, padx=20)
        self.server_name_var = tk.StringVar()
        ttk.Entry(frame, textvariable=self.server_name_var, width=50).pack(padx=20, pady=5)
        
        # Server host
        ttk.Label(frame, text="Server Host:").pack(anchor=tk.W, padx=20)
        self.server_host_var = tk.StringVar()
        ttk.Entry(frame, textvariable=self.server_host_var, width=50).pack(padx=20, pady=5)
        
        # Port configuration frame
        port_frame = ttk.LabelFrame(frame, text="Port Configuration")
        port_frame.pack(fill=tk.X, padx=20, pady=10)
        
        # Login port
        ttk.Label(port_frame, text="Login Port:").grid(row=0, column=0, sticky=tk.W, padx=5, pady=5)
        self.login_port_var = tk.StringVar()
        ttk.Entry(port_frame, textvariable=self.login_port_var, width=10).grid(row=0, column=1, padx=5, pady=5)
        
        # Map port
        ttk.Label(port_frame, text="Map Port:").grid(row=0, column=2, sticky=tk.W, padx=5, pady=5)
        self.map_port_var = tk.StringVar()
        ttk.Entry(port_frame, textvariable=self.map_port_var, width=10).grid(row=0, column=3, padx=5, pady=5)
        
        # Search port
        ttk.Label(port_frame, text="Search Port:").grid(row=1, column=0, sticky=tk.W, padx=5, pady=5)
        self.search_port_var = tk.StringVar()
        ttk.Entry(port_frame, textvariable=self.search_port_var, width=10).grid(row=1, column=1, padx=5, pady=5)
    
    def create_client_tab(self, notebook):
        """Create client configuration tab"""
        frame = ttk.Frame(notebook)
        notebook.add(frame, text="Client Settings")
        
        ttk.Label(frame, text="Client Configuration", font=('Arial', 12, 'bold')).pack(pady=10)
        
        # Client path
        ttk.Label(frame, text="FFXI Client Path:").pack(anchor=tk.W, padx=20)
        client_path_frame = ttk.Frame(frame)
        client_path_frame.pack(fill=tk.X, padx=20, pady=5)
        
        self.client_path_var = tk.StringVar()
        ttk.Entry(client_path_frame, textvariable=self.client_path_var, width=60).pack(side=tk.LEFT, fill=tk.X, expand=True)
        ttk.Button(client_path_frame, text="Browse", command=self.browse_client_path).pack(side=tk.RIGHT, padx=(5, 0))
        
        # Compatibility options
        compat_frame = ttk.LabelFrame(frame, text="Client Compatibility")
        compat_frame.pack(fill=tk.X, padx=20, pady=10)
        
        self.windower_compat_var = tk.BooleanVar()
        ttk.Checkbutton(compat_frame, text="Windower Compatible", variable=self.windower_compat_var).pack(anchor=tk.W, padx=5, pady=2)
        
        self.ashita_compat_var = tk.BooleanVar()
        ttk.Checkbutton(compat_frame, text="Ashita Compatible", variable=self.ashita_compat_var).pack(anchor=tk.W, padx=5, pady=2)
        
        self.auto_update_var = tk.BooleanVar()
        ttk.Checkbutton(compat_frame, text="Auto Update Client", variable=self.auto_update_var).pack(anchor=tk.W, padx=5, pady=2)
    
    def create_advanced_tab(self, notebook):
        """Create advanced settings tab"""
        frame = ttk.Frame(notebook)
        notebook.add(frame, text="Advanced")
        
        ttk.Label(frame, text="Advanced Settings", font=('Arial', 12, 'bold')).pack(pady=10)
        
        # Timeout settings
        timeout_frame = ttk.LabelFrame(frame, text="Timeout Settings")
        timeout_frame.pack(fill=tk.X, padx=20, pady=10)
        
        ttk.Label(timeout_frame, text="Client Timeout (ms):").grid(row=0, column=0, sticky=tk.W, padx=5, pady=5)
        self.client_timeout_var = tk.StringVar()
        ttk.Entry(timeout_frame, textvariable=self.client_timeout_var, width=10).grid(row=0, column=1, padx=5, pady=5)
        
        # Configuration files
        config_frame = ttk.LabelFrame(frame, text="Configuration Files")
        config_frame.pack(fill=tk.X, padx=20, pady=10)
        
        ttk.Button(config_frame, text="Load .env File", command=self.load_env_file).pack(side=tk.LEFT, padx=5, pady=5)
        ttk.Button(config_frame, text="Save .env File", command=self.save_env_file).pack(side=tk.LEFT, padx=5, pady=5)
        ttk.Button(config_frame, text="Export Ashita Config", command=self.export_ashita_config).pack(side=tk.LEFT, padx=5, pady=5)
    
    def create_launcher_tab(self, notebook):
        """Create launcher tab"""
        frame = ttk.Frame(notebook)
        notebook.add(frame, text="Launch")
        
        ttk.Label(frame, text="Launch FFXI Client", font=('Arial', 12, 'bold')).pack(pady=10)
        
        # Status display
        self.status_text = tk.Text(frame, height=15, width=80)
        self.status_text.pack(padx=20, pady=10, fill=tk.BOTH, expand=True)
        
        # Scrollbar for status text
        scrollbar = ttk.Scrollbar(self.status_text)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self.status_text.config(yscrollcommand=scrollbar.set)
        scrollbar.config(command=self.status_text.yview)
        
        # Buttons
        button_frame = ttk.Frame(frame)
        button_frame.pack(pady=10)
        
        ttk.Button(button_frame, text="Check Server Status", command=self.check_server_status).pack(side=tk.LEFT, padx=5)
        ttk.Button(button_frame, text="Launch Client", command=self.launch_client).pack(side=tk.LEFT, padx=5)
        ttk.Button(button_frame, text="Clear Log", command=self.clear_log).pack(side=tk.LEFT, padx=5)
    
    def load_current_config(self):
        """Load current configuration into GUI"""
        self.server_name_var.set(self.server_config.get('FFXI_SERVER_NAME'))
        self.server_host_var.set(self.server_config.get('FFXI_SERVER_HOST'))
        self.login_port_var.set(self.server_config.get('FFXI_LOGIN_PORT'))
        self.map_port_var.set(self.server_config.get('FFXI_MAP_PORT'))
        self.search_port_var.set(self.server_config.get('FFXI_SEARCH_PORT'))
        self.client_path_var.set(self.server_config.get('FFXI_CLIENT_PATH'))
        self.client_timeout_var.set(self.server_config.get('FFXI_CLIENT_TIMEOUT'))
        
        self.windower_compat_var.set(self.server_config.get('FFXI_WINDOWER_COMPATIBLE').lower() == 'true')
        self.ashita_compat_var.set(self.server_config.get('FFXI_ASHITA_COMPATIBLE').lower() == 'true')
        self.auto_update_var.set(self.server_config.get('FFXI_AUTO_UPDATE').lower() == 'true')
    
    def save_current_config(self):
        """Save current GUI configuration"""
        self.server_config.set('FFXI_SERVER_NAME', self.server_name_var.get())
        self.server_config.set('FFXI_SERVER_HOST', self.server_host_var.get())
        self.server_config.set('FFXI_LOGIN_PORT', self.login_port_var.get())
        self.server_config.set('FFXI_MAP_PORT', self.map_port_var.get())
        self.server_config.set('FFXI_SEARCH_PORT', self.search_port_var.get())
        self.server_config.set('FFXI_CLIENT_PATH', self.client_path_var.get())
        self.server_config.set('FFXI_CLIENT_TIMEOUT', self.client_timeout_var.get())
        
        self.server_config.set('FFXI_WINDOWER_COMPATIBLE', str(self.windower_compat_var.get()).lower())
        self.server_config.set('FFXI_ASHITA_COMPATIBLE', str(self.ashita_compat_var.get()).lower())
        self.server_config.set('FFXI_AUTO_UPDATE', str(self.auto_update_var.get()).lower())
    
    def browse_client_path(self):
        """Browse for FFXI client path"""
        path = filedialog.askdirectory(title="Select FFXI Client Directory")
        if path:
            self.client_path_var.set(path)
    
    def load_env_file(self):
        """Load configuration from .env file"""
        file_path = filedialog.askopenfilename(
            title="Select .env file",
            filetypes=[("Environment files", "*.env"), ("All files", "*.*")]
        )
        if file_path:
            self.server_config = FFXIServerConfig(file_path)
            self.ashita_generator = AshitaConfigGenerator(self.server_config)
            self.load_current_config()
            self.log_message(f"Loaded configuration from {file_path}")
    
    def save_env_file(self):
        """Save configuration to .env file"""
        file_path = filedialog.asksaveasfilename(
            title="Save .env file",
            defaultextension=".env",
            filetypes=[("Environment files", "*.env"), ("All files", "*.*")]
        )
        if file_path:
            self.save_current_config()
            self.server_config.env_file = file_path
            self.server_config.save()
            self.log_message(f"Saved configuration to {file_path}")
    
    def export_ashita_config(self):
        """Export Ashita configuration file"""
        file_path = filedialog.asksaveasfilename(
            title="Export Ashita configuration",
            defaultextension=".ini",
            filetypes=[("INI files", "*.ini"), ("All files", "*.*")]
        )
        if file_path:
            self.save_current_config()
            if self.ashita_generator.generate_config(file_path):
                self.log_message(f"Exported Ashita configuration to {file_path}")
                messagebox.showinfo("Success", f"Ashita configuration exported to {file_path}")
            else:
                self.log_message("Failed to export Ashita configuration")
                messagebox.showerror("Error", "Failed to export Ashita configuration")
    
    def check_server_status(self):
        """Check server status"""
        def check_status():
            self.log_message("Checking server status...")
            
            host = self.server_host_var.get() or 'localhost'
            login_port = self.login_port_var.get() or '54001'
            
            try:
                import socket
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(5)
                result = sock.connect_ex((host, int(login_port)))
                sock.close()
                
                if result == 0:
                    self.log_message(f"✅ Server is online at {host}:{login_port}")
                else:
                    self.log_message(f"❌ Server is offline or unreachable at {host}:{login_port}")
            except Exception as e:
                self.log_message(f"❌ Failed to check server status: {e}")
        
        threading.Thread(target=check_status, daemon=True).start()
    
    def launch_client(self):
        """Launch FFXI client with Ashita"""
        def launch():
            self.log_message("Preparing to launch FFXI client...")
            
            # Save current configuration
            self.save_current_config()
            
            # Generate temporary Ashita config
            temp_config_path = "temp_ashita_config.ini"
            if not self.ashita_generator.generate_config(temp_config_path):
                self.log_message("❌ Failed to generate Ashita configuration")
                return
            
            self.log_message("✅ Generated Ashita configuration")
            
            # Check for Ashita CLI
            ashita_cli_path = Path("ashita/Ashita-cli.exe")
            if not ashita_cli_path.exists():
                self.log_message("❌ Ashita CLI not found. Please ensure Ashita files are downloaded.")
                return
            
            try:
                # Launch Ashita with generated configuration
                cmd = [str(ashita_cli_path), "--config", temp_config_path]
                self.log_message(f"Launching: {' '.join(cmd)}")
                
                process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
                
                # Read output
                stdout, stderr = process.communicate(timeout=30)
                
                if process.returncode == 0:
                    self.log_message("✅ Client launched successfully")
                    if stdout:
                        self.log_message(f"Output: {stdout}")
                else:
                    self.log_message(f"❌ Client launch failed (exit code: {process.returncode})")
                    if stderr:
                        self.log_message(f"Error: {stderr}")
                
            except subprocess.TimeoutExpired:
                self.log_message("⚠️ Launch command timed out (this may be normal)")
            except Exception as e:
                self.log_message(f"❌ Failed to launch client: {e}")
            finally:
                # Clean up temporary config
                if Path(temp_config_path).exists():
                    Path(temp_config_path).unlink()
        
        threading.Thread(target=launch, daemon=True).start()
    
    def log_message(self, message: str):
        """Add message to status log"""
        timestamp = datetime.now().strftime("%H:%M:%S")
        formatted_message = f"[{timestamp}] {message}\n"
        
        self.status_text.insert(tk.END, formatted_message)
        self.status_text.see(tk.END)
        self.root.update()
    
    def clear_log(self):
        """Clear the status log"""
        self.status_text.delete(1.0, tk.END)
    
    def run(self):
        """Run the GUI"""
        self.root.mainloop()

def main():
    """Main entry point"""
    if len(sys.argv) > 1:
        # CLI mode
        if sys.argv[1] == '--generate-config':
            env_file = sys.argv[2] if len(sys.argv) > 2 else '.env'
            output_file = sys.argv[3] if len(sys.argv) > 3 else 'ashita_config.ini'
            
            config = FFXIServerConfig(env_file)
            generator = AshitaConfigGenerator(config)
            
            if generator.generate_config(output_file):
                print(f"✅ Generated Ashita configuration: {output_file}")
                print(f"Server: {config.get('FFXI_SERVER_NAME')}")
                print(f"Host: {config.get('FFXI_SERVER_HOST')}")
            else:
                print("❌ Failed to generate configuration")
                sys.exit(1)
        
        elif sys.argv[1] == '--check-server':
            env_file = sys.argv[2] if len(sys.argv) > 2 else '.env'
            config = FFXIServerConfig(env_file)
            
            import socket
            host = config.get('FFXI_SERVER_HOST', 'localhost')
            port = int(config.get('FFXI_LOGIN_PORT', '54001'))
            
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(5)
                result = sock.connect_ex((host, port))
                sock.close()
                
                if result == 0:
                    print(f"✅ Server is online at {host}:{port}")
                else:
                    print(f"❌ Server is offline or unreachable at {host}:{port}")
                    sys.exit(1)
            except Exception as e:
                print(f"❌ Failed to check server: {e}")
                sys.exit(1)
        
        else:
            print("FFXI Server Launcher")
            print("Usage:")
            print("  python ffxi_launcher.py                           - Launch GUI")
            print("  python ffxi_launcher.py --generate-config [env] [out] - Generate Ashita config")
            print("  python ffxi_launcher.py --check-server [env]      - Check server status")
    
    else:
        # GUI mode
        app = FFXILauncherGUI()
        app.run()

if __name__ == "__main__":
    main()